# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the githubactions branch
  push:
    branches: [ githubactions ]
  pull_request:
    branches: [ githubactions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  runs-on: ubuntu-latest
  steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo Hello from Octo Organization
   
       # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
